name: Run UFC Parser Every Hour

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  run-parser:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5   # ← обновлено с v4 на v5
      
      - name: Setup Python
        uses: actions/setup-python@v6   # ← обновлено с v5 на v6
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 pandas yadisk openpyxl
      
      - name: Run parser
        env:
          YA_TOKEN: ${{ secrets.YA_TOKEN }}
          BACKEND_URL: ${{ secrets.BACKEND_URL }}
        run: python ufc_parser.py