name: Run UFC Tournament Parser

on:
  schedule:
    - cron: '0 7 * * 4'   # четверг, 10:00 MSK (7:00 UTC)
    - cron: '0 7 * * 0'   # воскресенье, 10:00 MSK (7:00 UTC)
  workflow_dispatch:

jobs:
  run-parser:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          pip install selenium webdriver-manager requests beautifulsoup4 pandas yadisk openpyxl
      
      - name: Run parser
        env:
          YA_TOKEN: ${{ secrets.YA_TOKEN }}
          BACKEND_URL: ${{ secrets.BACKEND_URL }}
        run: python ufc_parser.py